/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_lpuart.h"
#include "fsl_clock.h"
#include "fsl_lpi2c.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Definition of peripheral ID */
#define LPUART_1_PERIPHERAL LPUART1
/* Definition of the clock source frequency */
#define LPUART_1_CLOCK_SOURCE 80000000UL
/* BOARD_InitPeripherals defines for LPI2C1 */
/* Definition of peripheral ID */
#define LPI2C_1_PERIPHERAL LPI2C1
/* Definition of clock source */
#define LPI2C_1_CLOCK_FREQ 60000000UL
/* Transfer buffer size */
#define LPI2C_1_MASTER_BUFFER_SIZE 1
/* Definition of slave address */
#define LPI2C_1_MASTER_SLAVE_ADDRESS 0
/* Definition of peripheral ID */
#define LPUART_2_PERIPHERAL LPUART2
/* Definition of the clock source frequency */
#define LPUART_2_CLOCK_SOURCE 80000000UL
/* Definition of peripheral ID */
#define LPUART_3_PERIPHERAL LPUART5
/* Definition of the clock source frequency */
#define LPUART_3_CLOCK_SOURCE 80000000UL

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const lpuart_config_t LPUART_1_config;
extern const lpi2c_master_config_t LPI2C_1_masterConfig;
extern lpi2c_master_transfer_t LPI2C_1_masterTransfer;
extern uint8_t LPI2C_1_masterBuffer[LPI2C_1_MASTER_BUFFER_SIZE];
extern lpi2c_master_handle_t LPI2C_1_masterHandle;
extern const lpuart_config_t LPUART_2_config;
extern const lpuart_config_t LPUART_3_config;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
